# Numpy Operations

In [4]:
# Numpy is the core library for scientific computing in python
# To provides a high performance multidimensional array object and tools for working with these arrays

In [2]:
# first install the numpy library using "pip" 

In [3]:
!pip install numpy

In [5]:
# now import the numpy giving alias as np

In [6]:
import numpy as np

In [7]:
# array creation using numpy

In [8]:
np_arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [10]:
np_arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Advantages of numpy over list

In [12]:
'''
1. Less memory
2. Fast
3. Convenient
'''

'\n1. Less memory\n2. Fast\n3. Convenient\n'

In [13]:
# Now let's compare the space taken up by the numpy vs array

In [14]:
import time
import sys

s = range(1000)
print(sys.getsizeof(s)*len(s))

d = np.arange(1000)
print(d.size*d.itemsize)

48000
4000


In [15]:
# lets check the time taken by the array and numpy array

In [16]:
SIZE = 100000

L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)


start = time.time()
result = A1 +A2
print((time.time()-start)*1000)

72.88360595703125
6.982326507568359


In [17]:
# Numpy Operations

# Find the dimension of the array
# Find the byte size of each element
# Find the data type of the elements

In [18]:
np_arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# ndim : Number of array dimensions.

In [20]:
print(np_arr1.ndim)

1


In [23]:
np_arr2 = np.array(
[[1,2,3,4],[5,6,7,11],[8,9,10,12]])

In [24]:
np_arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 11],
       [ 8,  9, 10, 12]])

In [25]:
print(np_arr2.ndim)

2


In [27]:
# itemsize : Length of one array element in bytes.

In [26]:
np_arr1.itemsize

4

In [30]:
np_arr2.itemsize

4

In [29]:
# dtype : Data-type of the array’s elements.

In [31]:
np_arr1.dtype

dtype('int32')

In [32]:
np_arr2.dtype

dtype('int32')

In [33]:
# size : Number of elements in the array.

In [34]:
np_arr1.size

10

In [35]:
np_arr2.size

12

In [36]:
# shape : Tuple of array dimensions.
'''
The shape property is usually used to get the current shape of an array, 
but may also be used to reshape the array in-place by assigning a tuple of array dimensions to it. 
As with numpy.reshape, one of the new shape dimensions can be -1, 
in which case its value is inferred from the size of the array and the remaining dimensions.
Reshaping an array in-place will fail if a copy is required.
'''


'\nThe shape property is usually used to get the current shape of an array, \nbut may also be used to reshape the array in-place by assigning a tuple of array dimensions to it. \nAs with numpy.reshape, one of the new shape dimensions can be -1, \nin which case its value is inferred from the size of the array and the remaining dimensions.\nReshaping an array in-place will fail if a copy is required.\n'

In [37]:
np_arr1.shape

(10,)

In [38]:
np_arr2.shape

(3, 4)

In [39]:
#  reshaping the array
'''
ndarray.resize(new_shape, refcheck=True)
Change shape and size of array in-place.
'''

'\nndarray.resize(new_shape, refcheck=True)\nChange shape and size of array in-place.\n'

In [40]:
a = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])

In [41]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
a = a.reshape(4,3)

In [44]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
# Slicing in numpy array

In [46]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
print(a[:,0]) # for printing the first coloum

[ 1  4  7 10]


In [50]:
print(a[0,:]) # for printing the first row

[1 2 3]


In [63]:
print(a[2:,1:])

[[ 8  9]
 [11 12]]


In [62]:
print(a[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [61]:
print(a[0:3,1:])

[[2 3]
 [5 6]
 [8 9]]


In [59]:
print(a[0:3,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
print(a[0:3,0:2])

[[1 2]
 [4 5]
 [7 8]]


In [53]:
print(a[:,1:2])

[[ 2]
 [ 5]
 [ 8]
 [11]]


In [54]:
print(a[1,:])

[4 5 6]


In [55]:
print(a[:,2])

[ 3  6  9 12]


In [56]:
print(a[3,:])

[10 11 12]


In [65]:
# linspace : numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
'''
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.
'''

'\nReturn evenly spaced numbers over a specified interval.\n\nReturns num evenly spaced samples, calculated over the interval [start, stop].\n\nThe endpoint of the interval can optionally be excluded.\n'

In [66]:
a = np.linspace(10,100,10)

In [67]:
a

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [68]:
b = np.linspace(50,100,10)

In [69]:
b

array([ 50.        ,  55.55555556,  61.11111111,  66.66666667,
        72.22222222,  77.77777778,  83.33333333,  88.88888889,
        94.44444444, 100.        ])

In [78]:
# max : char.chararray.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
#       Return the maximum along a given axis.

In [71]:
arr = np.array([1,2,3,4,5])

In [74]:
arr.max()

5

In [77]:
# min : ndarray.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
#        Return the minimum along a given axis.

In [75]:
arr.min()

1

In [79]:
# sum : ndarray.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)
#        Return the sum of the array elements over the given axis.

In [76]:
arr.sum()

15